USE [AtomicStat]
GO

CREATE UNIQUE NONCLUSTERED INDEX [ux01HashKCP] ON [kegen].[HashKCP]
(
	[BatchLogId] ASC,
	[ValidFI_CustomerId] ASC,
	[ValidFI_PayerId] ASC
)
INCLUDE([PartitionId],[KeyElementId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [FG_Kegen]
GO


