ALTER TABLE hadoop.HadoopBatchExecutionEvent ALTER COLUMN HadoopBatchExecutionStatusId smallint NOT NULL;
ALTER TABLE hadoop.HadoopBatchExecutionEvent ALTER COLUMN HadoopBatchTypeId smallint NOT NULL;
ALTER TABLE hadoop.HadoopBatchExecutionStatus ALTER COLUMN HadoopBatchExecutionStatusId smallint NOT NULL;
ALTER TABLE hadoop.HadoopBatchType ALTER COLUMN HadoopBatchTypeId smallint NOT NULL;
ALTER TABLE kegen.HashKCP ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE kegen.KCP_PNC_SurrogateKeyXref ALTER COLUMN BatchLogId smallint NOT NULL;
ALTER TABLE mtb.Hash ALTER COLUMN StatBatchLogId smallint NOT NULL;
ALTER TABLE mtb.MTBBatchStatBatchLogXref ALTER COLUMN MTBBatchId smallint NOT NULL;
ALTER TABLE mtb.MTBBatchStatBatchLogXref ALTER COLUMN StatBatchLogId smallint NOT NULL;
ALTER TABLE mtb.MTBBatchStatBatchLogXref_backup_20190316_0101 ALTER COLUMN MTBBatchId smallint NOT NULL;
ALTER TABLE mtb.MTBBatchStatBatchLogXref_backup_20190316_0101 ALTER COLUMN StatBatchLogId smallint NOT NULL;
ALTER TABLE mtb.MTBHashKey ALTER COLUMN StatBatchLogId smallint NOT NULL;
ALTER TABLE precalc.BatchRunValue ALTER COLUMN BatchLogId smallint NOT NULL;
ALTER TABLE precalc.Parameter ALTER COLUMN BatchLogId smallint NOT NULL;
ALTER TABLE report.KeyElement ALTER COLUMN BatchLogId smallint NOT NULL;
ALTER TABLE report.KeyReference ALTER COLUMN BatchLogId smallint NOT NULL;
ALTER TABLE stat.BatchLog ALTER COLUMN BatchLogId smallint NOT NULL;
ALTER TABLE stat.BatchLog ALTER COLUMN BatchProcessId smallint NOT NULL;
ALTER TABLE stat.KCPKeyElementXref ALTER COLUMN BatchLogId smallint NOT NULL;
ALTER TABLE stat.KeyElement ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatGroupMaxBatch ALTER COLUMN MaxBatchLogId smallint NOT NULL;
ALTER TABLE stat.StatTypeBigint ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeBit ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeDate ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeDatetime ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeDecimal1602 ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeFloat ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeInt ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeMoney ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeNchar100 ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeNchar50 ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeNumeric0109 ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeNumeric1019 ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeNumeric2028 ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE stat.StatTypeNumeric2938 ALTER COLUMN BatchLogId smallint NULL;
ALTER TABLE work.StatTypeDecimal1602 ALTER COLUMN BatchLogId smallint NULL;
